FROM node:lts AS development

WORKDIR /usr/src/app

COPY ./back/package*.json ./

RUN npm install glob rimraf

RUN npm install

COPY ./back .

RUN npm run build

CMD ["npm", "run", "start:dev"]


FROM node:lts AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY ./back/package*.json ./
RUN npm install

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]

EXPOSE 3005
