FROM node:lts

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY ./back/package*.json ./
RUN npm install

COPY . .

COPY --from=development /usr/src/app/dist ./dist

EXPOSE 3005

CMD ["node", "dist/main"]
